repos:
  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black
        language_version: python3
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.8.0
    hooks:
     - id: isort
       args: ["--profile", "black", "--filter-files"]
       verbose: true
  - repo: https://github.com/Quantco/pre-commit-mirrors-jupytext
    rev: 1.10.2
    hooks:
     - id: jupytext-conda
       args:
         - --to=py:percent
         - --pipe=black
         - --opt=notebook_metadata_filter=-kernelspec
