# Config for hyperparameter-tuning CPA on SciPlex 3 with pretrained (and frozen) HierVAE drug embeddings.
seml:
  executable: compert/seml_sweep_icb.py
  name: chemical_cpa_lincs
  output_dir: sweeps/logs
  conda_environment: chemical_CPA
  project_root_dir: ..

slurm:
  max_simultaneous_jobs: 1
  experiments_per_job: 1
  sbatch_options_template: GPU
  sbatch_options:
    gres: gpu:1       # num GPUs
    mem: 32G          # memory
    cpus-per-task: 6  # num cores
    time: 0-05:01     # max time, D-HH:MM
###### BEGIN PARAMETER CONFIGURATION ######

fixed:
  profiling.run_profiler: False
  profiling.outdir: "./"

  training.checkpoint_freq: 50 # checkpoint frequency to save intermediate results
  training.num_epochs: 1 # maximum epochs for training
  training.max_minutes: 300 # maximum computation time
  training.save_checkpoints: False
  training.run_eval_disentangle: True
  training.run_eval: True
  training.save_dir: sweeps/checkpoints
  
  model.additional_params.loss_ae: gauss # loss (currently only gaussian loss is supported)
  model.additional_params.patience: 20 # patience for early stopping
  model.additional_params.decoder_activation: linear # last layer of the decoder
  model.additional_params.seed: 1337 # random seed
  model.additional_params.doser_type: null # non-linearity for doser function

  dataset.dataset_type: lincs
  dataset.data_params.dataset_path: datasets/lincs_full_smiles.h5ad # full path to the anndata dataset
  dataset.data_params.perturbation_key: pert_id # stores name of the drug
  dataset.data_params.pert_category: cov_drug_dose_name # stores celltype_drugname_drugdose
  dataset.data_params.dose_key: pert_dose # stores drug dose as a float
  dataset.data_params.covariate_keys: cell_id # necessary field for cell types. Fill it with a dummy variable if no celltypes present.
  dataset.data_params.smiles_key: canonical_smiles
  dataset.data_params.split_key: split1 # necessary field for train, test, ood splits.
  dataset.data_params.use_drugs_idx: True


  model.hparams.adversary_depth: 4
  model.hparams.adversary_lr: 6.5e-05
  model.hparams.adversary_wd: 4.2e-05
  model.hparams.adversary_width: 128
  model.hparams.adversary_steps: 5

  model.hparams.autoencoder_depth: 4
  model.hparams.autoencoder_lr: 0.00148
  model.hparams.autoencoder_wd: 3.5e-08
  model.hparams.autoencoder_width: 256

  model.hparams.batch_size: 256
  model.hparams.dim: 256
  model.hparams.dosers_depth: 2
  model.hparams.dosers_lr: 0.00027322
  model.hparams.dosers_wd: 1.69e-07
  model.hparams.dosers_width: 64
  model.hparams.penalty_adversary: 0.050719
  model.hparams.reg_adversary: 92.6838
  model.hparams.step_size_lr: 15
  model.hparams.dropout: 0.1
  model.hparams.embedding_encoder_width: 512
  model.hparams.embedding_encoder_depth: 1

  model.embedding.directory: embeddings
  model.embedding.model: grover_base
