defaults: 
  - _self_
  - model:  finetune_2000_genes 
  - dataset: sciplex_2000_genes 
  - training: default 
  - wandb: default
  - hydra: default

profiling.run_profiler: False
profiling.outdir: "./"
